### ISSUE TITLE
Record & Remote dimensions data usage

### ISSUE THREAD

**Issue by wiebren** [newrelic/newrelic-prometheus-exporters-packages#94]
## Summary

Some of the metrics use dimensions "remote" or "record", for a public DNS server of any reasonable size this will cause a lot of data ingestion. There is no way de disable the specific metric or dimension.

## Desired Behavior

- Allow specific metrics to be disabled
- Allow specific dimensions to be disabled, e.g. keep the metric but only with a total value

**Comment by paologallinaharbur** [comment]
Hello!
In the integration sample there should be a snipped showing how to perform metric filtering :

Have you tried this approach?

```yaml
integrations:
    - name: nri-powerdns
      config:
[...]

        # transformations:
        #   - description: "General processing rules"
        #     ignore_metrics:
        #     - prefixes:
        #       - "go_"
        #       - "process_"
```
